Fix gtkrc-2.0 and update dmenu-mount/umount

diff --git a/.config/shell/aliasrc b/.config/shell/aliasrc
--- a/.config/shell/aliasrc
+++ b/.config/shell/aliasrc
@@ -29,8 +29,39 @@ ex ()
   fi
 }
 
-alias ls="ls -AF --color=auto --group-directories-first" \
-	lsl="ls -lh" \
+# useage: mkcd <directory>
+mkcd ()
+{
+	[ ! -z $1 ] && mkdir $1 && cd $1 || echo "'$1' cannot be made"
+}
+
+# sudo not required for some system commands.
+for command in mount umount pacman nmtui su shutdown poweroff reboot ; do
+	alias $command="sudo $command"
+done; unset command
+
+# Verbosity and settings that you pretty much just always are going to want.
+alias \
+	cp="cp -iv" \
+	mv="mv -iv" \
+	rm="rm -vI" \
+	bc="bc -ql" \
+	mkd="mkdir -pv" \
+	yt="yt-dlp --embed-metadata -i" \
+	yta="yt -x -f bestaudio/best" \
+	ffmpeg="ffmpeg -hide_banner"
+
+# Colorize commands when possible.
+alias \
+	ls="ls -hFN --color=auto --group-directories-first" \
+	grep="grep --color=auto" \
+	diff="diff --color=auto" \
+	ip="ip -color=auto"
+
+alias \
+	la="ls -A" \
+	ll="ls -l" \
+	lal="ls -lA" \
     myip="curl ifconfig.co" \
     pacman="pacman --color=auto" \
     yay="yay --color=auto" \
@@ -39,17 +70,12 @@ alias ls="ls -AF --color=auto --group-directories-first" \
     gradlew="gradle" \
     gradlew.bat="gradle" \
     xclip="xclip -selection clipboard" \
-    searchsploit="/opt/exploit-database/searchsploit" \
-    ..="cd .." \
     rr="curl -s -L http://bit.ly/10hA8iC | bash" \
     mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
     mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist" \
     mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist" \
     mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist" \
     cleanup="sudo pacman -Rncs $(pacman -Qtdq)" \
-    grep="grep --color=auto" \
-    egrep="egrep --color=auto" \
-    fgrep="fgrep --color=auto" \
     addup="git add -u" \
     addall="git add ." \
     branch="git branch" \
@@ -71,17 +97,36 @@ alias ls="ls -AF --color=auto --group-directories-first" \
     gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify" \
     gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys" \
     weather="curl wttr.in" \
-    sb="cd ~/.local/bin/" \
-    sbs="cd ~/.local/bin/statusbar" \
-    sbd="cd ~/.local/bin/dmenu-scripts" \
+	yarn="yarn --use-yarnrc ${XDG_CONFIG_HOME:-$HOME/.config}/yarn/config"
+
+# My many programing directories.
+alias \
 	coding="cd ~/Desktop/coding-stuff" \
 	codingb="cd ~/Desktop/coding-stuff/bash" \
 	codingc="cd ~/Desktop/coding-stuff/c" \
 	codingcp="cd ~/Desktop/coding-stuff/c++" \
 	codingcs="cd ~/Desktop/coding-stuff/c#" \
-	codingg="cd ~/Desktop/coding-stuff/github" \
-	codinggc="cd ~/Desktop/coding-stuff/github/clones" \
 	codingj="cd ~/Desktop/coding-stuff/java" \
 	codingjs="cd ~/Desktop/coding-stuff/javascript" \
-	codingp="cd ~/Desktop/coding-stuff/python" \
-	yarn="yarn --use-yarnrc ${XDG_CONFIG_HOME:-$HOME/.config}/yarn/config" \
+	codingp="cd ~/Desktop/coding-stuff/python"\
+	codingg="cd ~/Desktop/coding-stuff/github" \
+	codinggc="cd ~/Desktop/coding-stuff/github/clones" \
+	codinggcc="cd ~/Desktop/coding-stuff/github/clones/c" \
+	codinggcj="cd ~/Desktop/coding-stuff/github/clones/java" \
+	codinggcp="cd ~/Desktop/coding-stuff/github/clones/pythong" \
+	codinggcr="cd ~/Desktop/coding-stuff/github/clones/rust" \
+	codinggcw="cd ~/Desktop/coding-stuff/github/clones/web-dev"
+
+# My misc directories.
+alias \
+    ..="cd .." \
+	d="cd ~/Desktop" \
+	p="cd ~/Pictures" \
+	cf="cd ~/.config" \
+    sb="cd ~/.local/bin/" \
+    sbs="cd ~/.local/bin/statusbar" \
+    sbd="cd ~/.local/bin/dmenu-scripts" \
+	mnt="cd /mnt" \
+	mntu="cd /mnt/universal-files" \
+	mntur="cd /mnt/universal-files/recording-archive"
+
